name: Custom Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Run a custom script
        run: echo "This workflow only runs on the develop branch! Task 4 is successful!"